name: Android CI

on:
  push:
    branches:
      - ci-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build the project and run unit tests
      run: ./gradlew build
